/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as EditarRouteImport } from './routes/editar'
import { Route as GemasRouteImport } from './routes/gemas'
import { Route as RutaRouteImport } from './routes/ruta'
import { Route as TSlugRouteImport } from './routes/t.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarRoute = EditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const GemasRoute = GemasRouteImport.update({
  id: '/gemas',
  path: '/gemas',
  getParentRoute: () => rootRouteImport,
} as any)
const RutaRoute = RutaRouteImport.update({
  id: '/ruta',
  path: '/ruta',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/ayuda': typeof AyudaRoute
  '/editar': typeof EditarRoute
  '/gemas': typeof GemasRoute
  '/ruta': typeof RutaRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/ayuda': typeof AyudaRoute
  '/editar': typeof EditarRoute
  '/gemas': typeof GemasRoute
  '/ruta': typeof RutaRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/ayuda': typeof AyudaRoute
  '/editar': typeof EditarRoute
  '/gemas': typeof GemasRoute
  '/ruta': typeof RutaRoute
  '/t/$slug': typeof TSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/asistente' | '/ayuda' | '/editar' | '/gemas' | '/ruta' | '/t/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/asistente' | '/ayuda' | '/editar' | '/gemas' | '/ruta' | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/asistente'
    | '/ayuda'
    | '/editar'
    | '/gemas'
    | '/ruta'
    | '/t/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  AyudaRoute: typeof AyudaRoute
  EditarRoute: typeof EditarRoute
  GemasRoute: typeof GemasRoute
  RutaRoute: typeof RutaRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar': {
      id: '/editar'
      path: '/editar'
      fullPath: '/editar'
      preLoaderRoute: typeof EditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemas': {
      id: '/gemas'
      path: '/gemas'
      fullPath: '/gemas'
      preLoaderRoute: typeof GemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruta': {
      id: '/ruta'
      path: '/ruta'
      fullPath: '/ruta'
      preLoaderRoute: typeof RutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  AyudaRoute: AyudaRoute,
  EditarRoute: EditarRoute,
  GemasRoute: GemasRoute,
  RutaRoute: RutaRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
